import type { ReferentielMenuGroupId } from '@core/config/referentiel-routes.data';

/** Codes fonctionnalité alignés sur le menu (et {@link MenuRbacInitializer} côté API). */
export const MENU_FEATURES = {
  DASHBOARD: 'DASHBOARD',
  CENTRES_ALPHA: 'CENTRES_ALPHA',
  CENTRES_CEC: 'CENTRES_CEC',
  CENTRES_CP: 'CENTRES_CP',
  CENTRES_SIE: 'CENTRES_SIE',
  PERSONNEL: 'PERSONNEL',
  PROMOTEUR: 'PROMOTEUR',
  APPRENANT_EFFECTIF: 'APPRENANT_EFFECTIF',
  APPRENANT_ABANDON: 'APPRENANT_ABANDON',
  APPRENANT_PASSAGE: 'APPRENANT_PASSAGE',
  APPRENANT_HANDICAP: 'APPRENANT_HANDICAP',
  APPRENANT_ADMIS_CEPE: 'APPRENANT_ADMIS_CEPE',
  APPRENANT_INTEGRES_FORMEL_CP: 'APPRENANT_INTEGRES_FORMEL_CP',
  APPRENANT_ADMIS_TEST_INTEGRATION_CP: 'APPRENANT_ADMIS_TEST_INTEGRATION_CP',
  PARAMETRAGE_GEOGRAPHIE: 'PARAMETRAGE_GEOGRAPHIE',
  PARAMETRAGE_CENTRES_AUTORISATIONS: 'PARAMETRAGE_CENTRES_AUTORISATIONS',
  PARAMETRAGE_PEDAGOGIE: 'PARAMETRAGE_PEDAGOGIE',
  PARAMETRAGE_ACTIVITES_CENTRE: 'PARAMETRAGE_ACTIVITES_CENTRE',
  PARAMETRAGE_DOCUMENTS: 'PARAMETRAGE_DOCUMENTS',
  PARAMETRAGE_AUTRES: 'PARAMETRAGE_AUTRES',
  ADMIN_UTILISATEURS: 'ADMIN_UTILISATEURS',
  ADMIN_ACTEURS: 'ADMIN_ACTEURS',
  ADMIN_ROLE_PERMISSIONS: 'ADMIN_ROLE_PERMISSIONS',
  // Activités centre (déjà en place, conservés)
  ACTIVITES_CENTRE_PARTENARIAT: 'ACTIVITES_CENTRE_PARTENARIAT',
  ACTIVITES_CENTRE_PERFORMANCE: 'ACTIVITES_CENTRE_PERFORMANCE',
  ACTIVITES_CENTRE_CONTROLE: 'ACTIVITES_CENTRE_CONTROLE',
  ACTIVITES_CENTRE_EVALUATION: 'ACTIVITES_CENTRE_EVALUATION',
  ACTIVITES_CENTRE_INFOS: 'ACTIVITES_CENTRE_INFOS',
  POINTS_VISITES: 'POINTS_VISITES',
  SUIVI_CONSEILLER: 'SUIVI_CONSEILLER',
  SUIVI_SUPERVISEUR: 'SUIVI_SUPERVISEUR',
  SUIVI_IEPP: 'SUIVI_IEPP',
  SUIVI_CENTRALE: 'SUIVI_CENTRALE',
  VALIDATION_VISITES_CONSEILLER: 'VALIDATION_VISITES_CONSEILLER',
  SAISIE_DONNEES: 'SAISIE_DONNEES',
} as const;

export type MenuFeatureCode = (typeof MENU_FEATURES)[keyof typeof MENU_FEATURES];

/** Rôles qui voient tout le menu sans contrôle RBAC (administration technique). */
export const RBAC_BYPASS_ROLE_CODES = new Set([
  'SUPER_ROOT',
  'SUPER_ADMIN',
  'ADMIN',
]);

export const PARAMETRAGE_GROUP_FEATURE: Record<ReferentielMenuGroupId, MenuFeatureCode> = {
  geographie: MENU_FEATURES.PARAMETRAGE_GEOGRAPHIE,
  'centres-autorisations': MENU_FEATURES.PARAMETRAGE_CENTRES_AUTORISATIONS,
  pedagogie: MENU_FEATURES.PARAMETRAGE_PEDAGOGIE,
  'activites-centre': MENU_FEATURES.PARAMETRAGE_ACTIVITES_CENTRE,
  documents: MENU_FEATURES.PARAMETRAGE_DOCUMENTS,
  others: MENU_FEATURES.PARAMETRAGE_AUTRES,
};

/** Route Angular → fonctionnalité menu (accès lecture). */
export const ROUTE_MENU_FEATURE: Record<string, MenuFeatureCode> = {
  '': MENU_FEATURES.DASHBOARD,
  personnel: MENU_FEATURES.PERSONNEL,
  promoteurs: MENU_FEATURES.PROMOTEUR,
  'centres/alpha': MENU_FEATURES.CENTRES_ALPHA,
  'centres/alpha/nouveau': MENU_FEATURES.CENTRES_ALPHA,
  'centres/cec': MENU_FEATURES.CENTRES_CEC,
  'centres/cec/nouveau': MENU_FEATURES.CENTRES_CEC,
  'centres/cp': MENU_FEATURES.CENTRES_CP,
  'centres/cp/nouveau': MENU_FEATURES.CENTRES_CP,
  'centres/sie': MENU_FEATURES.CENTRES_SIE,
  'centres/sie/nouveau': MENU_FEATURES.CENTRES_SIE,
  'apprenant/effectif': MENU_FEATURES.APPRENANT_EFFECTIF,
  'apprenant/abandon': MENU_FEATURES.APPRENANT_ABANDON,
  'apprenant/passage': MENU_FEATURES.APPRENANT_PASSAGE,
  'apprenant/handicap': MENU_FEATURES.APPRENANT_HANDICAP,
  'apprenant/admis-cepe': MENU_FEATURES.APPRENANT_ADMIS_CEPE,
  'apprenant/integres-formel-cp': MENU_FEATURES.APPRENANT_INTEGRES_FORMEL_CP,
  'apprenant/admis-test-integration-cp': MENU_FEATURES.APPRENANT_ADMIS_TEST_INTEGRATION_CP,
  'administration/utilisateurs': MENU_FEATURES.ADMIN_UTILISATEURS,
  'administration/acteurs': MENU_FEATURES.ADMIN_ACTEURS,
  'administration/role-permissions': MENU_FEATURES.ADMIN_ROLE_PERMISSIONS,
  'activites-centre/dossier-centre': MENU_FEATURES.ACTIVITES_CENTRE_PARTENARIAT,
  'activites-centre/partenariat': MENU_FEATURES.ACTIVITES_CENTRE_PARTENARIAT,
  'activites-centre/performance': MENU_FEATURES.ACTIVITES_CENTRE_PERFORMANCE,
  'activites-centre/controle': MENU_FEATURES.ACTIVITES_CENTRE_CONTROLE,
  'activites-centre/evaluation-periodique': MENU_FEATURES.ACTIVITES_CENTRE_EVALUATION,
  'activites-centre/informations-centres': MENU_FEATURES.ACTIVITES_CENTRE_INFOS,
  'activites-centre/visite/conseiller': MENU_FEATURES.SUIVI_CONSEILLER,
  'activites-centre/visite/superviseur': MENU_FEATURES.SUIVI_SUPERVISEUR,
  'activites-centre/visite/iepp': MENU_FEATURES.SUIVI_IEPP,
  'activites-centre/visite/centrale': MENU_FEATURES.SUIVI_CENTRALE,
  anneescolaire: MENU_FEATURES.PARAMETRAGE_AUTRES,
};

export const ACTIVITES_CENTRE_MENU_PERMISSIONS: readonly string[] = [
  `${MENU_FEATURES.ACTIVITES_CENTRE_PARTENARIAT}:LIRE`,
  `${MENU_FEATURES.ACTIVITES_CENTRE_PERFORMANCE}:LIRE`,
  `${MENU_FEATURES.ACTIVITES_CENTRE_CONTROLE}:LIRE`,
  `${MENU_FEATURES.ACTIVITES_CENTRE_EVALUATION}:LIRE`,
  `${MENU_FEATURES.ACTIVITES_CENTRE_INFOS}:LIRE`,
  `${MENU_FEATURES.POINTS_VISITES}:LIRE`,
  `${MENU_FEATURES.POINTS_VISITES}:CREER`,
  `${MENU_FEATURES.SUIVI_CONSEILLER}:LIRE`,
  `${MENU_FEATURES.VALIDATION_VISITES_CONSEILLER}:VALIDER`,
  `${MENU_FEATURES.SUIVI_SUPERVISEUR}:LIRE`,
  `${MENU_FEATURES.SUIVI_IEPP}:LIRE`,
  `${MENU_FEATURES.SUIVI_CENTRALE}:LIRE`,
];
