import type { ReferentielFormField } from '@core/config/referentiel-form.types';

export const FK_PERIODE_ACTIVITE: ReferentielFormField = {
  key: 'idPeriodeActivite',
  label: 'Période activité',
  type: 'select',
  required: true,
  optionsApiPath: '/api/v1/PeriodeActivites',
  optionValueKey: 'id',
  optionLabelKeys: ['codePeriodeActivite', 'libellePeriodeActivite'],
  payloadAsObjectId: true,
};

export const FK_CENTRE_ALPHA: ReferentielFormField = {
  key: 'idCentre',
  label: 'Centre Alpha',
  type: 'select',
  required: true,
  optionsApiPath: '/api/v1/alpha',
  optionValueKey: 'idCentre',
  optionLabelKeys: ['codeType', 'libelle', 'codeCentre'],
  payloadAsObjectId: true,
};

export const FK_ANNEE_SCOLAIRE: ReferentielFormField = {
  key: 'idAnneeScolaire',
  label: 'Année scolaire',
  type: 'select',
  required: true,
  optionsApiPath: '/api/anneescolaire',
  optionValueKey: 'id',
  optionLabelKeys: ['debutAnneeScolaire', 'finAnneeScolaire'],
  payloadAsObjectId: true,
};

export const FK_NIVEAU_CP: ReferentielFormField = {
  key: 'idNiveauCp',
  label: 'Niveau CP',
  type: 'select',
  required: true,
  optionsApiPath: '/api/niveaucp',
  optionValueKey: 'id',
  optionLabelKeys: ['libelleNiveauCp'],
  payloadAsObjectId: true,
};

export const FK_CENTRE_CP: ReferentielFormField = {
  key: 'idCentre',
  label: 'Centre CP',
  type: 'select',
  required: true,
  optionsApiPath: '/api/cp',
  optionValueKey: 'idCentre',
  optionLabelKeys: ['codeType', 'libelle', 'codeCentre'],
  payloadAsObjectId: true,
};

export const FK_NIVEAU_SIE: ReferentielFormField = {
  key: 'idNiveauSie',
  label: 'Niveau SIE / CEC',
  type: 'select',
  required: true,
  optionsApiPath: '/api/niveausiecec',
  optionValueKey: 'id',
  optionLabelKeys: ['libelleNiveauSie'],
  payloadAsObjectId: true,
};

export const FK_CENTRE_CEC: ReferentielFormField = {
  key: 'idCentre',
  label: 'Centre CEC',
  type: 'select',
  required: true,
  optionsApiPath: '/api/cec',
  optionValueKey: 'idCentre',
  optionLabelKeys: ['codeType', 'libelle', 'codeCentre'],
  payloadAsObjectId: true,
};

function num(key: string, label: string): ReferentielFormField {
  return { key, label, type: 'number' };
}

/** Effectif abandon Alpha — POST attend des relations `{ id }` (entité JPA). */
export const EFFECTIF_ABANDON_ALPHA_CREATE_FIELDS: ReferentielFormField[] = [
  FK_PERIODE_ACTIVITE,
  FK_CENTRE_ALPHA,
  num('effectifAbandonAlphaNiveauHomme', 'Abandon — niveau (H)'),
  num('effectifAbandonAlphaNiveauFemme', 'Abandon — niveau (F)'),
  num('effectifAbandonAlphaMoins15F', 'Abandon — moins 15 F'),
  num('effectifAbandonAlphaMoins15H', 'Abandon — moins 15 H'),
  num('effectifAbandonAlphaMoins15IvoirienH', 'Abandon — moins 15 Ivoirien H'),
  num('effectifAbandonAlphaMoins15IvoirienF', 'Abandon — moins 15 Ivoirien F'),
  num('effectifAbandonAlphaMoins15HandicapH', 'Abandon — moins 15 Handicap H'),
  num('effectifAbandonAlphaMoins15HandicapF', 'Abandon — moins 15 Handicap F'),
  num('effectifAbandonAlpha1524F', 'Abandon — 15-24 F'),
  num('effectifAbandonAlpha1524H', 'Abandon — 15-24 H'),
  num('effectifAbandonAlpha1524IvoirienH', 'Abandon — 15-24 Ivoirien H'),
  num('effectifAbandonAlpha1524IvoirienF', 'Abandon — 15-24 Ivoirien F'),
  num('effectifAbandonAlpha1524HandicapH', 'Abandon — 15-24 Handicap H'),
  num('effectifAbandonAlpha1524HandicapF', 'Abandon — 15-24 Handicap F'),
  num('effectifAbandonAlpha2549F', 'Abandon — 25-49 F'),
  num('effectifAbandonAlpha2549H', 'Abandon — 25-49 H'),
  num('effectifAbandonAlpha2549IvoirienF', 'Abandon — 25-49 Ivoirien F'),
  num('effectifAbandonAlpha2549IvoirienH', 'Abandon — 25-49 Ivoirien H'),
  num('effectifAbandonAlpha2549HandicapH', 'Abandon — 25-49 Handicap H'),
  num('effectifAbandonAlpha2549HandicapF', 'Abandon — 25-49 Handicap F'),
  num('effectifAbandonAlpha50PlusF', 'Abandon — 50+ F'),
  num('effectifAbandonAlpha50PlusH', 'Abandon — 50+ H'),
  num('effectifAbandonAlpha50PlusIvoirienH', 'Abandon — 50+ Ivoirien H'),
  num('effectifAbandonAlpha50PlusIvoirienF', 'Abandon — 50+ Ivoirien F'),
  num('effectifAbandonAlpha50PlusHandicapH', 'Abandon — 50+ Handicap H'),
  num('effectifAbandonAlpha50PlusHandicapF', 'Abandon — 50+ Handicap F'),
  { key: 'causeAbandonAlpha', label: 'Cause abandon', type: 'text', maxLength: 4000 },
];

/**
 * Passage — uniquement centres Alpha (`/api/effectif-passage-alpha`). Pas d’entité/API passage pour CP, CEC ou SIE.
 * Clé alignée sur l’entité JPA (typo historique côté base) : `effectifApassageAlpha50PlusIvoirienF`.
 */
export const EFFECTIF_PASSAGE_ALPHA_CREATE_FIELDS: ReferentielFormField[] = [
  FK_PERIODE_ACTIVITE,
  FK_CENTRE_ALPHA,
  num('effectifPassageAlphaNiveauHomme', 'Passage — niveau (H)'),
  num('effectifPassageAlphaNiveauFemme', 'Passage — niveau (F)'),
  num('effectifPassageAlphaMoins15F', 'Passage — moins 15 F'),
  num('effectifPassageAlphaMoins15H', 'Passage — moins 15 H'),
  num('effectifPassageAlphaMoins15IvoirienH', 'Passage — moins 15 Ivoirien H'),
  num('effectifPassageAlphaMoins15IvoirienF', 'Passage — moins 15 Ivoirien F'),
  num('effectifPassageAlphaMoins15HandicapH', 'Passage — moins 15 Handicap H'),
  num('effectifPassageAlphaMoins15HandicapF', 'Passage — moins 15 Handicap F'),
  num('effectifPassageAlpha1524F', 'Passage — 15-24 F'),
  num('effectifPassageAlpha1524H', 'Passage — 15-24 H'),
  num('effectifPassageAlpha1524IvoirienH', 'Passage — 15-24 Ivoirien H'),
  num('effectifPassageAlpha1524IvoirienF', 'Passage — 15-24 Ivoirien F'),
  num('effectifPassageAlpha1524HandicapH', 'Passage — 15-24 Handicap H'),
  num('effectifPassageAlpha1524HandicapF', 'Passage — 15-24 Handicap F'),
  num('effectifPassageAlpha2549F', 'Passage — 25-49 F'),
  num('effectifPassageAlpha2549H', 'Passage — 25-49 H'),
  num('effectifPassageAlpha2549IvoirienF', 'Passage — 25-49 Ivoirien F'),
  num('effectifPassageAlpha2549IvoirienH', 'Passage — 25-49 Ivoirien H'),
  num('effectifPassageAlpha2549HandicapH', 'Passage — 25-49 Handicap H'),
  num('effectifPassageAlpha2549HandicapF', 'Passage — 25-49 Handicap F'),
  num('effectifPassageAlpha50PlusF', 'Passage — 50+ F'),
  num('effectifPassageAlpha50PlusH', 'Passage — 50+ H'),
  num('effectifPassageAlpha50PlusIvoirienH', 'Passage — 50+ Ivoirien H'),
  num('effectifApassageAlpha50PlusIvoirienF', 'Passage — 50+ Ivoirien F'),
  num('effectifPassageAlpha50PlusHandicapH', 'Passage — 50+ Handicap H'),
  num('effectifPassageAlpha50PlusHandicapF', 'Passage — 50+ Handicap F'),
];

/** `effectifSituationHandicapalphaNiveauFemme` : nom de propriété JSON tel que sérialisé par Jackson. */
export const EFFECTIF_HANDICAP_ALPHA_CREATE_FIELDS: ReferentielFormField[] = [
  FK_PERIODE_ACTIVITE,
  FK_CENTRE_ALPHA,
  num('effectifSituationHandicapAlphaNiveauHomme', 'Handicap — niveau (H)'),
  num('effectifSituationHandicapalphaNiveauFemme', 'Handicap — niveau (F)'),
  num('effectifSituationHandicapAlphaMoins15F', 'Handicap — moins 15 F'),
  num('effectifSituationHandicapAlphaMoins15H', 'Handicap — moins 15 H'),
  num('effectifSituationHandicapAlphaMoins15IvoirienH', 'Handicap — moins 15 Ivoirien H'),
  num('effectifSituationHandicapAlphaMoins15IvoirienF', 'Handicap — moins 15 Ivoirien F'),
  num('effectifSituationHandicapAlphaMoins15HandicapH', 'Handicap — moins 15 Handicap H'),
  num('effectifSituationHandicapAlphaMoins15HandicapF', 'Handicap — moins 15 Handicap F'),
  num('effectifSituationHandicapAlpha1524F', 'Handicap — 15-24 F'),
  num('effectifSituationHandicapAlpha1524H', 'Handicap — 15-24 H'),
  num('effectifSituationHandicapAlpha1524IvoirienH', 'Handicap — 15-24 Ivoirien H'),
  num('effectifSituationHandicapAlpha1524IvoirienF', 'Handicap — 15-24 Ivoirien F'),
  num('effectifSituationHandicapAlpha1524HandicapH', 'Handicap — 15-24 Handicap H'),
  num('effectifSituationHandicapAlpha1524HandicapF', 'Handicap — 15-24 Handicap F'),
  num('effectifSituationHandicapAlpha2549F', 'Handicap — 25-49 F'),
  num('effectifSituationHandicapAlpha2549H', 'Handicap — 25-49 H'),
  num('effectifSituationHandicapAlpha2549IvoirienF', 'Handicap — 25-49 Ivoirien F'),
  num('effectifSituationHandicapAlpha2549IvoirienH', 'Handicap — 25-49 Ivoirien H'),
  num('effectifSituationHandicapAlpha2549HandicapH', 'Handicap — 25-49 Handicap H'),
  num('effectifSituationHandicapAlpha2549HandicapF', 'Handicap — 25-49 Handicap F'),
  num('effectifSituationHandicapAlpha50PlusF', 'Handicap — 50+ F'),
  num('effectifSituationHandicapAlpha50PlusH', 'Handicap — 50+ H'),
  num('effectifSituationHandicapAlpha50PlusIvoirienH', 'Handicap — 50+ Ivoirien H'),
  num('effectifSituationHandicapAlpha50PlusIvoirienF', 'Handicap — 50+ Ivoirien F'),
  num('effectifSituationHandicapAlpha50PlusHandicapH', 'Handicap — 50+ Handicap H'),
  num('effectifSituationHandicapAlpha50PlusHandicapF', 'Handicap — 50+ Handicap F'),
];

export const COMPETENCE_CENTRE_CREATE_FIELDS: ReferentielFormField[] = [
  {
    key: 'idCompetence',
    label: 'Compétence',
    type: 'select',
    required: true,
    optionsApiPath: '/api/competence',
    optionValueKey: 'id',
    optionLabelKeys: ['codeCompetence', 'libelleCompetence'],
    payloadAsObjectId: true,
  },
  { ...FK_CENTRE_ALPHA, label: 'Centre Alpha (compétence)' },
];

/** Abandon CP — `/api/effectif-abandon-cp` */
export const EFFECTIF_ABANDON_CP_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_NIVEAU_CP,
  FK_CENTRE_CP,
  num('effectifAbandonCp911IvoirienH', 'Abandon CP — 9-11 Ivoirien H'),
  num('effectifAbandonCp911IvoirienF', 'Abandon CP — 9-11 Ivoirien F'),
  num('effectifAbandonCp911HandicapH', 'Abandon CP — 9-11 Handicap H'),
  num('effectifAbandonCp911HandicapF', 'Abandon CP — 9-11 Handicap F'),
  num('effectifAbandonCp911NonIvoirienF', 'Abandon CP — 9-11 Non Ivoirien F'),
  num('effectifAbandonCp911NonIvoirienH', 'Abandon CP — 9-11 Non Ivoirien H'),
  num('effectifAbandonCp1213IvoirienF', 'Abandon CP — 12-13 Ivoirien F'),
  num('effectifAbandonCp1213IvoirienH', 'Abandon CP — 12-13 Ivoirien H'),
  num('effectifAbandonCp1213HandicapH', 'Abandon CP — 12-13 Handicap H'),
  num('effectifAbandonCp1213HandicapF', 'Abandon CP — 12-13 Handicap F'),
  num('effectifAbandonCp1213NonIvoiriienH', 'Abandon CP — 12-13 Non Ivoirien H'),
  num('effectifAbandonCp14IvoirienH', 'Abandon CP — 14 Ivoirien H'),
  num('effectifAbandonCp14IvoirienF', 'Abandon CP — 14 Ivoirien F'),
  num('effectifAbandonCp14HandicapH', 'Abandon CP — 14 Handicap H'),
  num('effectifAbandonCp14HandicapF', 'Abandon CP — 14 Handicap F'),
  num('effectifAbandonCp14NonIvoirienF', 'Abandon CP — 14 Non Ivoirien F'),
  num('effectifAbandonCp14NonIvoirienH', 'Abandon CP — 14 Non Ivoirien H'),
  num('effectifAbandonCpNiveauCp', 'Abandon CP — effectif niveau'),
  { key: 'causeAbandonCp', label: 'Cause abandon', type: 'text', maxLength: 4000 },
];

/** Abandon CEC — `/api/effectif-abandon-cec` */
export const EFFECTIF_ABANDON_CEC_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_NIVEAU_SIE,
  FK_CENTRE_CEC,
  num('effectifAbandonCecMoins3F', 'Abandon CEC — moins 3 F'),
  num('effectifAbandonCecMoins3H', 'Abandon CEC — moins 3 H'),
  num('effectifAbandonCecMoins3IvoirienH', 'Abandon CEC — moins 3 Ivoirien H'),
  num('effectifAbandonCecMoins3IvoirienF', 'Abandon CEC — moins 3 Ivoirien F'),
  num('effectifAbandonCecMoins3HandicapH', 'Abandon CEC — moins 3 Handicap H'),
  num('effectifAbandonCecMoins3HandicapF', 'Abandon CEC — moins 3 Handicap F'),
  num('effectifAbandonCec35F', 'Abandon CEC — 3-5 F'),
  num('effectifAbandonCec35H', 'Abandon CEC — 3-5 H'),
  num('effectifAbandonCec35IvoirienH', 'Abandon CEC — 3-5 Ivoirien H'),
  num('effectifAbandonCec35IvoirienF', 'Abandon CEC — 3-5 Ivoirien F'),
  num('effectifAbandonCec35HandicapH', 'Abandon CEC — 3-5 Handicap H'),
  num('effectifAbandonCec35HandicapF', 'Abandon CEC — 3-5 Handicap F'),
  num('effectifAbandonCec68F', 'Abandon CEC — 6-8 F'),
  num('effectifAbandonCec68H', 'Abandon CEC — 6-8 H'),
  num('effectifAbandonCec68IvoirienF', 'Abandon CEC — 6-8 Ivoirien F'),
  num('effectifAbandonCec68IvoirienH', 'Abandon CEC — 6-8 Ivoirien H'),
  num('effectifAbandonCec68HandicapH', 'Abandon CEC — 6-8 Handicap H'),
  num('effectifAbandonCec68HandicapF', 'Abandon CEC — 6-8 Handicap F'),
  num('effectifAbandonCec911H', 'Abandon CEC — 9-11 H'),
  num('effectifAbandonCec911F', 'Abandon CEC — 9-11 F'),
  num('effectifAbandonCec911IvoirienH', 'Abandon CEC — 9-11 Ivoirien H'),
  num('effectifAbandonCec911IvoirienF', 'Abandon CEC — 9-11 Ivoirien F'),
  num('effectifAbandonCec911HandicapH', 'Abandon CEC — 9-11 Handicap H'),
  num('effectifAbandonCec911HandicapF', 'Abandon CEC — 9-11 Handicap F'),
  num('effectifAbandonCec1216F', 'Abandon CEC — 12-16 F'),
  num('effectifAbandonCec1216H', 'Abandon CEC — 12-16 H'),
  num('effectifAbandonCec1216IvoirienH', 'Abandon CEC — 12-16 Ivoirien H'),
  num('effectifAbandonCec1216IvoirienF', 'Abandon CEC — 12-16 Ivoirien F'),
  num('effectifAbandonCec1216HandicapH', 'Abandon CEC — 12-16 Handicap H'),
  num('effectifAbandonCec1216HandicapF', 'Abandon CEC — 12-16 Handicap F'),
  num('effectifAbandonCecNiveauCec', 'Abandon CEC — effectif niveau'),
  { key: 'causeAbandonCec', label: 'Cause abandon', type: 'text', maxLength: 4000 },
];

/**
 * Abandon SIE — `/api/effectif-abondan-sie` (orthographe API historique).
 * Pas de centre en base : année + niveau SIE uniquement.
 */
export const EFFECTIF_ABONDAN_SIE_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_NIVEAU_SIE,
  num('effectifAbandonSie3IvoirienH', 'Abandon SIE — 3 Ivoirien H'),
  num('effectifAbandonSie3IvoirienF', 'Abandon SIE — 3 Ivoirien F'),
  num('effectifAbandonSie3HandicapH', 'Abandon SIE — 3 Handicap H'),
  num('effectifAbandonSie3HandicapF', 'Abandon SIE — 3 Handicap F'),
  num('effectifAbandonSie3NonIvoirienF', 'Abandon SIE — 3 Non Ivoirien F'),
  num('effectifAbandonSie3NonIvoirienH', 'Abandon SIE — 3 Non Ivoirien H'),
  num('effectifAbandonSie46IvoirienF', 'Abandon SIE — 4-6 Ivoirien F'),
  num('effectifAbandonSie46IvoirienH', 'Abandon SIE — 4-6 Ivoirien H'),
  num('effectifAbandonSie46HandicapH', 'Abandon SIE — 4-6 Handicap H'),
  num('effectifAbandonSie46HandicapF', 'Abandon SIE — 4-6 Handicap F'),
  num('effectifAbandonSie46NonIvoiriienH', 'Abandon SIE — 4-6 Non Ivoirien H'),
  num('effectifAbandonSie46NonIvoiriienF', 'Abandon SIE — 4-6 Non Ivoirien F'),
  num('effectifAbandonSie79IvoirienH', 'Abandon SIE — 7-9 Ivoirien H'),
  num('effectifAbandonSie79IvoirienF', 'Abandon SIE — 7-9 Ivoirien F'),
  num('effectifAbandonSie79HandicapH', 'Abandon SIE — 7-9 Handicap H'),
  num('effectifAbandonSie79HandicapF', 'Abandon SIE — 7-9 Handicap F'),
  num('effectifAbandonSie79NonIvoirienF', 'Abandon SIE — 7-9 Non Ivoirien F'),
  num('effectifAbandonSie79NonIvoirienH', 'Abandon SIE — 7-9 Non Ivoirien H'),
  num('effectifAbandonSie1012IvoirienF', 'Abandon SIE — 10-12 Ivoirien F'),
  num('effectifAbandonSie1012IvoirienH', 'Abandon SIE — 10-12 Ivoirien H'),
  num('effectifAbandonSie1012HandicapH', 'Abandon SIE — 10-12 Handicap H'),
  num('effectifAbandonSie1012HandicapF', 'Abandon SIE — 10-12 Handicap F'),
  num('effectifAbandonSie1012NonIvoirienH', 'Abandon SIE — 10-12 Non Ivoirien H'),
  num('effectifAbandonSie1012NonIvoirienF', 'Abandon SIE — 10-12 Non Ivoirien F'),
  num('effectifAbandonSie1314EtPlusIvoirienF', 'Abandon SIE — 13-14+ Ivoirien F'),
  num('effectifAbandonSie1314EtPlusIvoirienH', 'Abandon SIE — 13-14+ Ivoirien H'),
  num('effectifAbandonSie1314EtPlusHandicapF', 'Abandon SIE — 13-14+ Handicap F'),
  num('effectifAbandonSie1314EtPlusHandicapH', 'Abandon SIE — 13-14+ Handicap H'),
  num('effectifAbandonSie1314EtPlusNonIvoirienF', 'Abandon SIE — 13-14+ Non Ivoirien F'),
  num('effectifAbandonSie1314EtPlusNonIvoirienH', 'Abandon SIE — 13-14+ Non Ivoirien H'),
  num('effectifAbandonSieNiveauSie', 'Abandon SIE — effectif niveau'),
  { key: 'causeAbandonSie', label: 'Cause abandon', type: 'text', maxLength: 4000 },
];

/** Handicap CP — `/api/effectif-situation-handicap-cp` */
export const EFFECTIF_HANDICAP_CP_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_NIVEAU_CP,
  FK_CENTRE_CP,
  num('effectifSituationHandicapCp911IvoirienH', 'Handicap CP — 9-11 Ivoirien H'),
  num('effectifSituationHandicapCp911IvoirienF', 'Handicap CP — 9-11 Ivoirien F'),
  num('effectifSituationHandicapCp911HandicapH', 'Handicap CP — 9-11 Handicap H'),
  num('effectifSituationHandicapCp911HandicapF', 'Handicap CP — 9-11 Handicap F'),
  num('effectifSituationHandicapCp911NonIvoirienF', 'Handicap CP — 9-11 Non Ivoirien F'),
  num('effectifSituationHandicapCp911NonIvoirienH', 'Handicap CP — 9-11 Non Ivoirien H'),
  num('effectifSituationHandicapCp1213IvoirienF', 'Handicap CP — 12-13 Ivoirien F'),
  num('effectifSituationHandicapCp1213IvoirienH', 'Handicap CP — 12-13 Ivoirien H'),
  num('effectifSituationHandicapCp1213HandicapH', 'Handicap CP — 12-13 Handicap H'),
  num('effectifSituationHandicapCp1213HandicapF', 'Handicap CP — 12-13 Handicap F'),
  num('effectifSituationHandicapCp1213NonIvoiriienH', 'Handicap CP — 12-13 Non Ivoirien H'),
  num('effectifSituationHandicapCp1213NonIvoiriienF', 'Handicap CP — 12-13 Non Ivoirien F'),
  num('effectifSituationHandicapCp14IvoirienH', 'Handicap CP — 14 Ivoirien H'),
  num('effectifSituationHandicapCp14IvoirienF', 'Handicap CP — 14 Ivoirien F'),
  num('effectifSituationHandicapCp14HandicapH', 'Handicap CP — 14 Handicap H'),
  num('effectifSituationHandicapCp14HandicapF', 'Handicap CP — 14 Handicap F'),
  num('effectifSituationHandicapCp14NonIvoirienF', 'Handicap CP — 14 Non Ivoirien F'),
  num('effectifSituationHandicapCp14NonIvoirienH', 'Handicap CP — 14 Non Ivoirien H'),
  num('effectifSituationHandicapCpNiveauCp', 'Handicap CP — effectif niveau'),
];

/** Handicap CEC — `/api/effectif-situation-handicap-cec` (pas de centre en base). */
export const EFFECTIF_HANDICAP_CEC_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_NIVEAU_SIE,
  num('effectifSituationHandicapCecMoins3F', 'Handicap CEC — moins 3 F'),
  num('effectifSituationHandicapCecMoins3H', 'Handicap CEC — moins 3 H'),
  num('effectifSituationHandicapCecMoins3IvoirienH', 'Handicap CEC — moins 3 Ivoirien H'),
  num('effectifSituationHandicapCecMoins3IvoirienF', 'Handicap CEC — moins 3 Ivoirien F'),
  num('effectifSituationHandicapCec35F', 'Handicap CEC — 3-5 F'),
  num('effectifSituationHandicapCec35H', 'Handicap CEC — 3-5 H'),
  num('effectifSituationHandicapCec35IvoirienH', 'Handicap CEC — 3-5 Ivoirien H'),
  num('effectifSituationHandicapCec35IvoirienF', 'Handicap CEC — 3-5 Ivoirien F'),
  num('effectifSituationHandicapCec68F', 'Handicap CEC — 6-8 F'),
  num('effectifSituationHandicapCec68H', 'Handicap CEC — 6-8 H'),
  num('effectifSituationHandicapCec68IvoirienF', 'Handicap CEC — 6-8 Ivoirien F'),
  num('effectifSituationHandicapCec68IvoirienH', 'Handicap CEC — 6-8 Ivoirien H'),
  num('effectifSituationHandicapCec911IvoirienH', 'Handicap CEC — 9-11 Ivoirien H'),
  num('effectifSituationHandicapCec911IvoirienF', 'Handicap CEC — 9-11 Ivoirien F'),
  num('effectifSituationHandicapCec1216F', 'Handicap CEC — 12-16 F'),
  num('effectifSituationHandicapCec1216H', 'Handicap CEC — 12-16 H'),
  num('effectifSituationHandicapCec1216IvoirienH', 'Handicap CEC — 12-16 Ivoirien H'),
  num('effectifSituationHandicapCec1216IvoirienF', 'Handicap CEC — 12-16 Ivoirien F'),
  num('effectifSituationHandicapCecNiveauCec', 'Handicap CEC — effectif niveau'),
];

/** Handicap SIE — `/api/effectif-situation-handicap-sie` (clé Jackson avec typo historique sur 10-12 H). */
export const EFFECTIF_HANDICAP_SIE_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_NIVEAU_SIE,
  num('effectifSituationHandicapSie3IvoirienH', 'Handicap SIE — 3 Ivoirien H'),
  num('effectifSituationHandicapSie3IvoirienF', 'Handicap SIE — 3 Ivoirien F'),
  num('effectifSituationHandicapSie3NonIvoirienF', 'Handicap SIE — 3 Non Ivoirien F'),
  num('effectifSituationHandicapSie3NonIvoirienH', 'Handicap SIE — 3 Non Ivoirien H'),
  num('effectifSituationHandicapSie46IvoirienF', 'Handicap SIE — 4-6 Ivoirien F'),
  num('effectifSituationHandicapSie46IvoirienH', 'Handicap SIE — 4-6 Ivoirien H'),
  num('effectifSituationHandicapSie79IvoirienH', 'Handicap SIE — 7-9 Ivoirien H'),
  num('effectifSituationHandicapSie79IvoirienF', 'Handicap SIE — 7-9 Ivoirien F'),
  num('effectifSituationHandicapSie79NonIvoirienF', 'Handicap SIE — 7-9 Non Ivoirien F'),
  num('effectifSituationHandicapSie79NonIvoirienH', 'Handicap SIE — 7-9 Non Ivoirien H'),
  num('effectifSituationHandicapSie1012IvoirienF', 'Handicap SIE — 10-12 Ivoirien F'),
  num('effectifSituationHandicapSie1012IvoirienH', 'Handicap SIE — 10-12 Ivoirien H'),
  num('effectifSituationHandicaplSie1012NonIvoirienH', 'Handicap SIE — 10-12 Non Ivoirien H'),
  num('effectifSituationHandicapSie1012NonIvoirienF', 'Handicap SIE — 10-12 Non Ivoirien F'),
  num('effectifSituationHandicapSie1314EtPlusIvoirienF', 'Handicap SIE — 13-14+ Ivoirien F'),
  num('effectifSituationHandicapSie1314EtPlusIvoirienH', 'Handicap SIE — 13-14+ Ivoirien H'),
  num('effectifSituationHandicapSieNiveauSie', 'Handicap SIE — effectif niveau'),
];
