import type { ReferentielFormField } from '@core/config/referentiel-form.types';

import {
  FK_ANNEE_SCOLAIRE,
  FK_CENTRE_CEC,
  FK_CENTRE_CP,
  FK_NIVEAU_CP,
  FK_NIVEAU_SIE,
} from './effectif-satellite-forms.data';

function num(key: string, label: string): ReferentielFormField {
  return { key, label, type: 'number' };
}

/** Deuxième FK CEC (`cecIdCentre` côté JPA) — même liste `/api/cec`, libellé distinct. */
const FK_CEC_ID_CENTRE: ReferentielFormField = {
  key: 'cecIdCentre',
  label: 'Centre CEC (liaison)',
  type: 'select',
  required: true,
  optionsApiPath: '/api/cec',
  optionValueKey: 'idCentre',
  optionLabelKeys: ['codeType', 'libelle', 'codeCentre'],
  payloadAsObjectId: true,
};

/** CEPE — candidats / admis, centre CP — `/api/effectif-cepe-cp` */
export const EFFECTIF_CEPE_CP_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_CENTRE_CP,
  num('effectifCepeCandidatFCp', 'CEPE CP — candidates F'),
  num('effectifCepeCandidatHCp', 'CEPE CP — candidats H'),
  num('effectifCepeCandidatIvoirienCp', 'CEPE CP — candidats ivoiriens'),
  num('effectifCepeCandidatHandicapFCp', 'CEPE CP — candidates handicap F'),
  num('effectifCepeCandidatHandicapHCp', 'CEPE CP — candidats handicap H'),
  num('effectifCepeAdmisFCp', 'CEPE CP — admises F'),
  num('effectifCepeAdmisHCp', 'CEPE CP — admis H'),
  num('effectifCepeAdmisIvoirienCp', 'CEPE CP — admis ivoiriens'),
  num('effectifCepeAdmisHandicapFCp', 'CEPE CP — admises handicap F'),
  num('effectifCepeAdmisHandicapHCp', 'CEPE CP — admis handicap H'),
];

/** CEPE — deux centres CEC — `/api/effectif-cepe-cec` */
export const EFFECTIF_CEPE_CEC_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  { ...FK_CENTRE_CEC, label: 'Centre CEC (principal)' },
  FK_CEC_ID_CENTRE,
  num('effectifCepeCandidatFilleCec', 'CEPE CEC — candidates'),
  num('effectifCepeCandidatGarconCec', 'CEPE CEC — garçons candidats'),
  num('effectifCepeCandidatIvoirienCec', 'CEPE CEC — candidats ivoiriens'),
  num('effectifCepeCandidatHandicapFilleCec', 'CEPE CEC — candidates handicap'),
  num('effectifCepeCandidatHandicapGarconCec', 'CEPE CEC — garçons handicap'),
  num('effectifCepeAdmisFilleCec', 'CEPE CEC — admises'),
  num('effectifCepeAdmisGarconCec', 'CEPE CEC — garçons admis'),
  num('effectifCepeAdmisIvoirienCec', 'CEPE CEC — admis ivoiriens'),
  num('effectifCepeAdmisHandicapFilleCec', 'CEPE CEC — admises handicap'),
  num('effectifCepeAdmisHandicapGarconCec', 'CEPE CEC — garçons admis handicap'),
];

/** Admis intégration CP — `/api/effectif-admis-integration-cp` */
export const EFFECTIF_ADMIS_INTEGRATION_CP_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_NIVEAU_CP,
  FK_CENTRE_CP,
  num('effectifAdmisIntegrationCp911IvoirienH', 'Admis intégration — 9-11 Ivoirien H'),
  num('effectifAdmisIntegrationCp911IvoirienF', 'Admis intégration — 9-11 Ivoirien F'),
  num('effectifAdmisIntegrationCp911HandicapH', 'Admis intégration — 9-11 Handicap H'),
  num('effectifAdmisIntegrationCp911HandicapF', 'Admis intégration — 9-11 Handicap F'),
  num('effectifAdmisIntegrationCp911NonIvoirienF', 'Admis intégration — 9-11 Non Ivoirien F'),
  num('effectifAdmisIntegrationCp911NonIvoirienH', 'Admis intégration — 9-11 Non Ivoirien H'),
  num('effectifAdmisIntegrationCp1213IvoirienF', 'Admis intégration — 12-13 Ivoirien F'),
  num('effectifAdmisIntegrationCp1213IvoirienH', 'Admis intégration — 12-13 Ivoirien H'),
  num('effectifAdmisIntegrationCp1213HandicapH', 'Admis intégration — 12-13 Handicap H'),
  num('effectifAdmisIntegrationCp1213HandicapF', 'Admis intégration — 12-13 Handicap F'),
  num('effectifAdmisIntegrationCp1213NonIvoiriienH', 'Admis intégration — 12-13 Non Ivoirien H'),
  num('effectifAdmisIntegrationCp1213NonIvoiriienF', 'Admis intégration — 12-13 Non Ivoirien F'),
  num('effectifAdmisIntegrationCp14IvoirienH', 'Admis intégration — 14 Ivoirien H'),
  num('effectifAdmisIntegrationCp14IvoirienF', 'Admis intégration — 14 Ivoirien F'),
  num('effectifAdmisIntegrationCp14HandicapH', 'Admis intégration — 14 Handicap H'),
  num('effectifAdmisIntegrationCp14HandicapF', 'Admis intégration — 14 Handicap F'),
  num('effectifAdmisIntegrationCp14NonIvoirienF', 'Admis intégration — 14 Non Ivoirien F'),
  num('effectifAdmisIntegrationCp14NonIvoirienH', 'Admis intégration — 14 Non Ivoirien H'),
  num('effectifAdmisIntegrationCpNiveauCp', 'Admis intégration — effectif niveau'),
];

/** Intégration formelle CP — `/api/effectif-integration-formel-cp` */
export const EFFECTIF_INTEGRATION_FORMEL_CP_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_NIVEAU_CP,
  FK_CENTRE_CP,
  num('effectifIntegrationFormelCp911IvoirienH', 'Intégration formelle — 9-11 Ivoirien H'),
  num('effectifIntegrationFormelCp911IvoirienF', 'Intégration formelle — 9-11 Ivoirien F'),
  num('effectifIntegrationFormelCp911HandicapH', 'Intégration formelle — 9-11 Handicap H'),
  num('effectifIntegrationFormelCp911HandicapF', 'Intégration formelle — 9-11 Handicap F'),
  num('effectifIntegrationFormelCp911NonIvoirienF', 'Intégration formelle — 9-11 Non Ivoirien F'),
  num('effectifIntegrationFormelCp911NonIvoirienH', 'Intégration formelle — 9-11 Non Ivoirien H'),
  num('effectifIntegrationFormelCp1213IvoirienF', 'Intégration formelle — 12-13 Ivoirien F'),
  num('effectifIntegrationFormelCp1213IvoirienH', 'Intégration formelle — 12-13 Ivoirien H'),
  num('effectifIntegrationFormelCp1213HandicapH', 'Intégration formelle — 12-13 Handicap H'),
  num('effectifIntegrationFormelCp1213HandicapF', 'Intégration formelle — 12-13 Handicap F'),
  num('effectifIntegrationFormelCp1213NonIvoiriienH', 'Intégration formelle — 12-13 Non Ivoirien H'),
  num('effectifIntegrationFormelCp1213NonIvoiriienF', 'Intégration formelle — 12-13 Non Ivoirien F'),
  num('effectifIntegrationFormelCp14IvoirienH', 'Intégration formelle — 14 Ivoirien H'),
  num('effectifIntegrationFormelCp14IvoirienF', 'Intégration formelle — 14 Ivoirien F'),
  num('effectifIntegrationFormelCp14HandicapH', 'Intégration formelle — 14 Handicap H'),
  num('effectifIntegrationFormelCp14HandicapF', 'Intégration formelle — 14 Handicap F'),
  num('effectifIntegrationFormelCp14NonIvoirienF', 'Intégration formelle — 14 Non Ivoirien F'),
  num('effectifIntegrationFormelCp14NonIvoirienH', 'Intégration formelle — 14 Non Ivoirien H'),
  num('effectifIntegrationFormelCpNiveauCp', 'Intégration formelle — effectif niveau'),
];

/** Promu SIE — pas de centre — `/api/effectif-promu-sie` */
export const EFFECTIF_PROMU_SIE_CREATE_FIELDS: ReferentielFormField[] = [
  FK_ANNEE_SCOLAIRE,
  FK_NIVEAU_SIE,
  num('effectifPromuSie3IvoirienH', 'Promu SIE — 3 Ivoirien H'),
  num('effectifPromuSie3IvoirienF', 'Promu SIE — 3 Ivoirien F'),
  num('effectifPromuSie3HandicapH', 'Promu SIE — 3 Handicap H'),
  num('effectifPromuSie3HandicapF', 'Promu SIE — 3 Handicap F'),
  num('effectifPromuSie3NonIvoirienF', 'Promu SIE — 3 Non Ivoirien F'),
  num('effectifPromuSie3NonIvoirienH', 'Promu SIE — 3 Non Ivoirien H'),
  num('effectifPromuSie46IvoirienF', 'Promu SIE — 4-6 Ivoirien F'),
  num('effectifPromuSie46IvoirienH', 'Promu SIE — 4-6 Ivoirien H'),
  num('effectifPromuSie46HandicapH', 'Promu SIE — 4-6 Handicap H'),
  num('effectifPromuSie46HandicapF', 'Promu SIE — 4-6 Handicap F'),
  num('effectifPromuSie46NonIvoiriienH', 'Promu SIE — 4-6 Non Ivoirien H'),
  num('effectifPromuSie46NonIvoiriienF', 'Promu SIE — 4-6 Non Ivoirien F'),
  num('effectifPromuSie79IvoirienH', 'Promu SIE — 7-9 Ivoirien H'),
  num('effectifPromuSie79IvoirienF', 'Promu SIE — 7-9 Ivoirien F'),
  num('effectifPromuSie79HandicapH', 'Promu SIE — 7-9 Handicap H'),
  num('effectifPromuSie79HandicapF', 'Promu SIE — 7-9 Handicap F'),
  num('effectifPromuSie79NonIvoirienF', 'Promu SIE — 7-9 Non Ivoirien F'),
  num('effectifPromuSie79NonIvoirienH', 'Promu SIE — 7-9 Non Ivoirien H'),
  num('effectifPromuSie1012IvoirienF', 'Promu SIE — 10-12 Ivoirien F'),
  num('effectifPromuSie1012IvoirienH', 'Promu SIE — 10-12 Ivoirien H'),
  num('effectifPromuSie1012HandicapH', 'Promu SIE — 10-12 Handicap H'),
  num('effectifPromuSie1012HandicapF', 'Promu SIE — 10-12 Handicap F'),
  num('effectifPromuSie1012NonIvoirienH', 'Promu SIE — 10-12 Non Ivoirien H'),
  num('effectifPromuSie1012NonIvoirienF', 'Promu SIE — 10-12 Non Ivoirien F'),
  num('effectifPromuSie1314EtPlusIvoirienF', 'Promu SIE — 13-14+ Ivoirien F'),
  num('effectifPromuSie1314EtPlusIvoirienH', 'Promu SIE — 13-14+ Ivoirien H'),
  num('effectifPromuSie1314EtPlusHandicapF', 'Promu SIE — 13-14+ Handicap F'),
  num('effectifPromuSie1314EtPlusHandicapH', 'Promu SIE — 13-14+ Handicap H'),
  num('effectifPromuSieNiveauSie', 'Promu SIE — effectif niveau'),
];

/** Promu CEC — `/api/effectif-promu-cec` */
export const EFFECTIF_PROMU_CEC_CREATE_FIELDS: ReferentielFormField[] = [
  FK_NIVEAU_SIE,
  FK_ANNEE_SCOLAIRE,
  FK_CENTRE_CEC,
  num('effectifPromuCecMoins3F', 'Promu CEC — moins 3 F'),
  num('effectifPromuCecMoins3H', 'Promu CEC — moins 3 H'),
  num('effectifPromuCecMoins3IvoirienH', 'Promu CEC — moins 3 Ivoirien H'),
  num('effectifPromuCecMoins3IvoirienF', 'Promu CEC — moins 3 Ivoirien F'),
  num('effectifPromuCecMoins3HandicapH', 'Promu CEC — moins 3 Handicap H'),
  num('effectifPromuCecMoins3HandicapF', 'Promu CEC — moins 3 Handicap F'),
  num('effectifPromuCec35F', 'Promu CEC — 3-5 F'),
  num('effectifPromuCec35H', 'Promu CEC — 3-5 H'),
  num('effectifPromuCec35IvoirienH', 'Promu CEC — 3-5 Ivoirien H'),
  num('effectifPromuCec35IvoirienF', 'Promu CEC — 3-5 Ivoirien F'),
  num('effectifPromuCec35HandicapH', 'Promu CEC — 3-5 Handicap H'),
  num('effectifPromuCec35HandicapF', 'Promu CEC — 3-5 Handicap F'),
  num('effectifPromuCec68F', 'Promu CEC — 6-8 F'),
  num('effectifPromuCec68H', 'Promu CEC — 6-8 H'),
  num('effectifPromuCec68IvoirienF', 'Promu CEC — 6-8 Ivoirien F'),
  num('effectifPromuCec68IvoirienH', 'Promu CEC — 6-8 Ivoirien H'),
  num('effectifPromuCec68HandicapH', 'Promu CEC — 6-8 Handicap H'),
  num('effectifPromuCec68HandicapF', 'Promu CEC — 6-8 Handicap F'),
  num('effectifPromuCec911H', 'Promu CEC — 9-11 H'),
  num('effectifPromuCec911F', 'Promu CEC — 9-11 F'),
  num('effectifPromuCec911IvoirienH', 'Promu CEC — 9-11 Ivoirien H'),
  num('effectifPromuCec911IvoirienF', 'Promu CEC — 9-11 Ivoirien F'),
  num('effectifPromuCec911HandicapH', 'Promu CEC — 9-11 Handicap H'),
  num('effectifPromuCec911HandicapF', 'Promu CEC — 9-11 Handicap F'),
  num('effectifPromuCec1216F', 'Promu CEC — 12-16 F'),
  num('effectifPromuCec1216H', 'Promu CEC — 12-16 H'),
  num('effectifPromuCec1216IvoirienH', 'Promu CEC — 12-16 Ivoirien H'),
  num('effectifPromuCec1216IvoirienF', 'Promu CEC — 12-16 Ivoirien F'),
  num('effectifPromuCec1216HandicapH', 'Promu CEC — 12-16 Handicap H'),
  num('effectifPromuCec1216HandicapF', 'Promu CEC — 12-16 Handicap F'),
  num('effectifPromuCecNiveauCec', 'Promu CEC — effectif niveau'),
];

/** Reverse formel SIE — pas de centre — `/api/effectif-reverse-formel-sie` */
export const EFFECTIF_REVERSE_FORMEL_SIE_CREATE_FIELDS: ReferentielFormField[] = [
  FK_NIVEAU_SIE,
  FK_ANNEE_SCOLAIRE,
  num('effectifReverseFormelSie3IvoirienH', 'Reverse formel SIE — 3 Ivoirien H'),
  num('effectifReverseFormelSie3IvoirienF', 'Reverse formel SIE — 3 Ivoirien F'),
  num('effectifReverseFormelSie3HandicapH', 'Reverse formel SIE — 3 Handicap H'),
  num('effectifReverseFormelSie3HandicapF', 'Reverse formel SIE — 3 Handicap F'),
  num('effectifReverseFormelSie3NonIvoirienF', 'Reverse formel SIE — 3 Non Ivoirien F'),
  num('effectifReverseFormelSie3NonIvoirienH', 'Reverse formel SIE — 3 Non Ivoirien H'),
  num('effectifReverseFormelSie46IvoirienF', 'Reverse formel SIE — 4-6 Ivoirien F'),
  num('effectifReverseFormelSie46IvoirienH', 'Reverse formel SIE — 4-6 Ivoirien H'),
  num('effectifReverseFormelSie46HandicapH', 'Reverse formel SIE — 4-6 Handicap H'),
  num('effectifReverseFormelSie46HandicapF', 'Reverse formel SIE — 4-6 Handicap F'),
  num('effectifReverseFormelSie46NonIvoiriienH', 'Reverse formel SIE — 4-6 Non Ivoirien H'),
  num('effectifReverseFormelSie46NonIvoiriienF', 'Reverse formel SIE — 4-6 Non Ivoirien F'),
  num('effectifReverseFormelSie79IvoirienH', 'Reverse formel SIE — 7-9 Ivoirien H'),
  num('effectifReverseFormelSie79IvoirienF', 'Reverse formel SIE — 7-9 Ivoirien F'),
  num('effectifReverseFormelSie79HandicapH', 'Reverse formel SIE — 7-9 Handicap H'),
  num('effectifReverseFormelSie79HandicapF', 'Reverse formel SIE — 7-9 Handicap F'),
  num('effectifReverseFormelSie79NonIvoirienF', 'Reverse formel SIE — 7-9 Non Ivoirien F'),
  num('effectifReverseFormelSie79NonIvoirienH', 'Reverse formel SIE — 7-9 Non Ivoirien H'),
  num('effectifReverseFormelSie1012IvoirienF', 'Reverse formel SIE — 10-12 Ivoirien F'),
  num('effectifReverseFormelSie1012IvoirienH', 'Reverse formel SIE — 10-12 Ivoirien H'),
  num('effectifReverseFormelSie1012HandicapH', 'Reverse formel SIE — 10-12 Handicap H'),
  num('effectifReverseFormelSie1012HandicapF', 'Reverse formel SIE — 10-12 Handicap F'),
  num('effectifReverseFormelSie1012NonIvoirienH', 'Reverse formel SIE — 10-12 Non Ivoirien H'),
  num('effectifReverseFormelSie1012NonIvoirienF', 'Reverse formel SIE — 10-12 Non Ivoirien F'),
  num('effectifReverseFormelSie1314EtPlusIvoirienF', 'Reverse formel SIE — 13-14+ Ivoirien F'),
  num('effectifReverseFormelSie1314EtPlusIvoirienH', 'Reverse formel SIE — 13-14+ Ivoirien H'),
  num('effectifReverseFormelSie1314EtPlusHandicapF', 'Reverse formel SIE — 13-14+ Handicap F'),
  num('effectifReverseFormelSie1314EtPlusHandicapH', 'Reverse formel SIE — 13-14+ Handicap H'),
  num('effectifReverseFormelSieNiveauSie', 'Reverse formel SIE — effectif niveau'),
];
